version: '3.8'

services:
  flask-app:
    build: .
    ports:
      - "8080:9696"
    environment:
      - FLASK_ENV=development
      - MONGO_URI=mongodb://mongo:27017/mydatabase # This will be the connection string for your app
    volumes:
      - .:/app
    restart: unless-stopped
    depends_on:
      - mongo # Ensure mongo starts before flask-app

  mongo:
    image: mongo:latest
    ports:
      - "27018:27017" # Map host port 27018 to container port 27017
    volumes:
      - mongo_data:/data/db # Persist data
    restart: unless-stopped

volumes:
  mongo_data: